build:
  nodes:
    analysis:
      dependencies:
        before:
          - composer require codeception/codeception:^4.1
      environment:
        php:
          version: 7.4
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      environment:
        php:
          version: 7.4
          pecl_extensions:
            - zip
        hosts:
          dev.local: '127.0.0.1'
        apache2:
          modules: ['rewrite']
          sites:
            local:
              host: 'dev.local'
              web_root: 'src/'
        selenium: true
        google_chrome:
          use_latest: true
      services:
      tests:
        before:
          - cp -rT src/tests/www src/
          - (cd src/ && composer require codeception/module-webdriver codeception/module-asserts --dev)

        override:
          - command: (cd src/ && ./vendor/bin/codecept build && ./vendor/bin/codecept run --coverage-xml -v)
            coverage:
              file: src/tests/_output/coverage.xml
              format: clover

filter:
    paths: ["src/PHPMV/*"]
    excluded_paths:

checks:
    php:
        code_rating: true
        duplication: true